version: "3.9"

# 生产部署：直接拉取已在 CI 构建并推送到私有仓库的镜像
# 可通过设置环境变量 TAG 指定版本（默认 latest），例如: TAG=sha-xxxx docker compose up -d
services:
    backend:
        image: docker.pumpking.life/image-opt-backend:${TAG:-latest}
        container_name: image-opt-backend
        environment:
            NODE_ENV: production
        ports:
            - "3001:3001"
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://localhost:3001/health"]
            interval: 30s
            timeout: 5s
            retries: 3
            start_period: 10s

    frontend:
        image: docker.pumpking.life/image-opt-frontend:${TAG:-latest}
        container_name: image-opt-frontend
        depends_on:
            - backend
        ports:
            - "${FRONTEND_PORT:-18080}:80" # 可通过环境变量 FRONTEND_PORT 覆盖
        restart: unless-stopped
# 用法:
# 1) 登录私有仓库: docker login docker.pumpking.life
# 2) 拉取镜像(可选): docker compose pull
# 3) 启动: docker compose up -d  (默认前端对外 18080)
# 4) 访问: http://<服务器IP>:18080
# 如需改端口: FRONTEND_PORT=30080 docker compose up -d
# 指定特定标签: TAG=2025-08-26-1 docker compose up -d

# 若需要固定版本，可直接写死: image: docker.pumpking.life/image-opt-backend:1.0.0
