name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "npm"
            - name: Install root deps
              run: npm install --workspaces
            - name: Backend build
              run: npm --workspace backend run build
            - name: Frontend build
              run: npm --workspace frontend run build
            - name: Lint
              run: npm run lint
            - name: Test
              run: npm test
            - name: Archive frontend dist
              uses: actions/upload-artifact@v4
              with:
                  name: frontend-dist
                  path: frontend/dist
