name: Build and Push Images

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build-and-push:
        name: Build & Push (frontend + backend)
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write

        env:
            REGISTRY: docker.pumpking.life
            IMAGE_NAME_BACKEND: image-opt-backend
            IMAGE_NAME_FRONTEND: image-opt-frontend
            DEFAULT_TAG: latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up QEMU (multi-arch optional)
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
                  password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

            - name: Extract meta (backend)
              id: meta_backend
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BACKEND }}
                  tags: |
                      type=raw,value=${{ env.DEFAULT_TAG }}
                      type=ref,event=branch
                      type=ref,event=tag
                      type=sha

            - name: Extract meta (frontend)
              id: meta_frontend
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_FRONTEND }}
                  tags: |
                      type=raw,value=${{ env.DEFAULT_TAG }}
                      type=ref,event=branch
                      type=ref,event=tag
                      type=sha

            - name: Build & push backend image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: Dockerfile.backend
                  push: true
                  platforms: linux/amd64
                  tags: ${{ steps.meta_backend.outputs.tags }}
                  labels: ${{ steps.meta_backend.outputs.labels }}
                  cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BACKEND }}:buildcache
                  cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BACKEND }}:buildcache,mode=max

            - name: Build & push frontend image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: Dockerfile.frontend
                  push: true
                  platforms: linux/amd64
                  tags: ${{ steps.meta_frontend.outputs.tags }}
                  labels: ${{ steps.meta_frontend.outputs.labels }}
                  cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME_FRONTEND }}:buildcache
                  cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME_FRONTEND }}:buildcache,mode=max

            - name: Summary
              run: |
                  echo "Backend image tags:\n${{ steps.meta_backend.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
                  echo "Frontend image tags:\n${{ steps.meta_frontend.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
